### PR TITLE
changed test topic's name

### PR DESCRIPTION
**Pull request by desmax74**
Changed test topic name from logs (name used by kafka) to testlogs  @danielezonca @jiripetrlik @mariofusco

### CODE REVIEW

**Comment by danielezonca** [comment]
Compilation succeed but let's try again

jenkins retest this please

**Comment by desmax74** [comment]
jenkins retest this please

**Comment by desmax74** [comment]
jenkins retest this please

**Comment by desmax74** [comment]
jenkins retest this please

**Comment by danielezonca** [comment]
jenkins retest this please

**Comment by danielezonca** [comment]
jenkins retest this please

**Comment by desmax74** [comment]
jenkins retest this please

**Comment by danielezonca** [comment]
jenkins retest this please

**Comment by danielezonca** [comment]
jenkins retest this please

**Comment by danielezonca** [comment]
jenkins retest this please

**Pull request merged**
