### PR TITLE
Fix snapshot test random failure

### PR DESCRIPTION
**Pull request by desmax74**
@jiripetrlik @danielezonca

### CODE REVIEW

**Comment by desmax74** [comment]
jenkins test this

**Comment by desmax74** [comment]
jenkins test this

**Comment by desmax74** [comment]
jenkins test this

**Comment by desmax74** [comment]
jenkins test this

**Comment by jiripetrlik** [comment]
jenkins retest this

**Comment by desmax74** [comment]
jenkins retest this

**Comment by jiripetrlik** [comment]
@desmax74 
Please remove new changes introduced in "removed useless code" commit. These changes were introduced after last code review and are not related to PR.

**Pull request closed without merging**
