### PR TITLE
[Drools-4550] Fixing inconsistencies between kie parent 

### PR DESCRIPTION
**Pull request by desmax74**
Replaced javax deps with org.jboss.spec.javax

@mareknovotny @jiripetrlik @danielezonca @mariofusco

### CODE REVIEW

**Comment by mareknovotny** [comment]
ok, thanks @desmax74 just one note this PR includes also the changes in https://github.com/kiegroup/openshift-drools-hacep/pull/43

**Comment by desmax74** [comment]
@mareknovotny do you prefer without the changes in the https://github.com/kiegroup/openshift-drools-hacep/pull/43 ?

**Comment by mareknovotny** [comment]
@desmax74 I don't care too much, but that was just a comment to explain that if you have all changes here I or merging person needs to close mine ;)

**Comment by desmax74** [comment]
@mareknovotny if you merge your PR,  your changes here will be included automatically and not signed as diff, but since your PR wasn't yet merged I've added here to include your here if the other PR isn't merged soon. Feel free to merge your, all the review was ok but is still open.

**Comment by mareknovotny** [comment]
@desmax74 ok, np, I merged both, please backport this into 7.26.x branch too

**Comment by desmax74** [comment]
@mareknovotny  Ok I'll  create the 7.26.x backport

**Pull request merged**
