### PR TITLE
Update snapshot versions and fix build failures

### PR DESCRIPTION
**Pull request by jiripetrlik**
Recreating https://github.com/kiegroup/openshift-drools-hacep/pull/5 because of PR check problems.

### CODE REVIEW

**Comment by danielezonca** [comment]
jenkins retest this please

**Comment by danielezonca** [comment]
@mbiarnes @mareknovotny 
The build is still failing.
In the log I can see this error that is not available in other repos logs
`Cloning repository https://github.com/kiegroup/openshift-drools-hacep.git
 > git init /home/jenkins/workspace/KIE/master/pullrequest/openshift-drools-hacep-pullrequests # timeout=10
ERROR: Reference path does not exist: /home/jenkins/git-repos/openshift-drools-hacep.git
Fetching upstream changes from https://github.com/kiegroup/openshift-drools-hacep.git`

I don't know if it is related.

**Comment by jiripetrlik** [comment]
@danielezonca @mbiarnes @mareknovotny 
It seems to me that it fails somewhere in execution server tests. So, probably unrelated to HA CEP. Correct me if I'm wrong. @mbiarnes Can you please increase memory limit for build. Why 4GBs is enough if droolsjbpm integration, which is also part of the build has in its PR check 8GB?

**Comment by mbiarnes** [comment]
Jenkins retest this please

**Comment by mbiarnes** [comment]
Jenkins retest this please

**Pull request merged**
