### PR TITLE
RHDM-1093 fixing inconsistences between kie-parent

### PR DESCRIPTION
**Pull request by mareknovotny**
https://issues.jboss.org/browse/RHDM-1093

### CODE REVIEW

**Comment by mareknovotny** [comment]
I believe there are more, as kie-parent uses instead of some standard APIs the org.jboss ones like https://github.com/kiegroup/droolsjbpm-build-bootstrap/blob/master/pom.xml#L4607-L4611 or https://github.com/kiegroup/droolsjbpm-build-bootstrap/blob/master/pom.xml#L4627-L4631, but I will decide you to change that

**Comment by jiripetrlik** [comment]
@mareknovotny 
Looks good to me. Regression tests passed on real OpenShift cluster. However, we have regression tests only for Spring boot. @desmax74 Can you please look at Thorntail part?

@mareknovotny Will you create cherry-pick for 7.26.x branch?

**Comment by desmax74** [comment]
@jiripetrlik which errors have you found ? Springboot and Thorntail starts correctly on minishift

**Comment by mareknovotny** [comment]
@desmax74 I think @jiripetrlik didn't write it failed for Thorntail, only QE doesn't have tests to run for that deployment ;)

**Comment by desmax74** [comment]
@mareknovotny ah ok :)

**Pull request merged**
